# Generated by Django 5.1.1 on 2024-10-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_conversation_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
