# Generated by Django 5.1.1 on 2024-10-06 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese'), ('Korean', 'Korean'), ('Japanese', 'Japanese'), ('Phillipino', 'Phillipino'), ('Vietnamese', 'Vietnamese'), ('Thai', 'Thai'), ('French', 'French'), ('German', 'German'), ('Greek', 'Greek'), ('Middle Eastern', 'Middle Eastern'), ('African', 'African'), ('Caribbean', 'Caribbean'), ('Brazilian', 'Brazilian'), ('American', 'American'), ('Indian', 'Indian'), ('English', 'English'), ('N/A', 'N/A')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Dessert', 'Dessert'), ('N/A', 'N/A')], max_length=64)),
                ('style', models.CharField(choices=[('Fried', 'Fried'), ('Grilled', 'Grilled'), ('Baked', 'Baked'), ('Steamed', 'Steamed'), ('Boiled', 'Boiled'), ('Raw', 'Raw'), ('Stir Fried', 'Stir Fried'), ('Braised', 'Braised'), ('Roasted', 'Roasted'), ('Meal Prep', 'Meal Prep'), ('N/A', 'N/A')], max_length=64)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('N/A', 'N/A')], max_length=64)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.cuisine')),
            ],
        ),
    ]
