# Generated by Django 5.1.1 on 2024-10-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese'), ('Korean', 'Korean'), ('Japanese', 'Japanese'), ('Phillipino', 'Phillipino'), ('Vietnamese', 'Vietnamese'), ('Thai', 'Thai'), ('French', 'French'), ('German', 'German'), ('Greek', 'Greek'), ('Middle Eastern', 'Middle Eastern'), ('African', 'African'), ('Caribbean', 'Caribbean'), ('Brazilian', 'Brazilian'), ('American', 'American'), ('Indian', 'Indian'), ('English', 'English'), ('N/A', 'N/A')], max_length=64),
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
    ]
