# Generated by Django 5.1.1 on 2024-10-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cuisine_delete_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese'), ('Korean', 'Korean'), ('Japanese', 'Japanese'), ('Phillipino', 'Phillipino'), ('Vietnamese', 'Vietnamese'), ('Thai', 'Thai'), ('French', 'French'), ('German', 'German'), ('Greek', 'Greek'), ('Middle Eastern', 'Middle Eastern'), ('African', 'African'), ('Caribbean', 'Caribbean'), ('Brazilian', 'Brazilian'), ('American', 'American'), ('Indian', 'Indian'), ('English', 'English'), ('N/A', 'N/A')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('N/A', 'N/A')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Dessert', 'Dessert'), ('N/A', 'N/A')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='style',
            field=models.CharField(choices=[('Fried', 'Fried'), ('Grilled', 'Grilled'), ('Baked', 'Baked'), ('Steamed', 'Steamed'), ('Boiled', 'Boiled'), ('Raw', 'Raw'), ('Stir Fried', 'Stir Fried'), ('Braised', 'Braised'), ('Roasted', 'Roasted'), ('Meal Prep', 'Meal Prep'), ('N/A', 'N/A')], max_length=64, null=True),
        ),
    ]
