# Generated by Django 5.1.1 on 2024-10-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, unique=True)),
                ('conversations', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
            ],
        ),
    ]
