# Generated by Django 5.1.1 on 2024-10-30 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_user_email_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
