# Generated by Django 5.1.1 on 2024-11-08 03:39

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0006_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.CharField(max_length=64, unique=True)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2024, 11, 21, 22, 39, 23, 658720))),
            ],
        ),
    ]
