# Generated by Django 5.1.1 on 2024-11-27 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0007_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 7, 42, 44, 954074)),
        ),
    ]
