# Generated by Django 5.1.1 on 2024-11-28 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0015_alter_session_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 16, 18, 32, 201901)),
        ),
    ]
